import os, json, base64, random, stringimport os, json, base64, random, stringimport os, json, base64, random, string
from cryptography.hazmat.primitives.kdf.scrypt import Scrypt
from cryptography.fernet import Fernet, InvalidToken

VAULT_FILE = "vault.json"
SALT_SIZE = 16

def derive(password, salt):
    k = Scrypt(salt=salt, length=32, n=2**14, r=8, p=1)
        return base64.urlsafe_b64encode(k.derive(password.encode()))

        def encrypt_vault(data, password):
            salt = os.urandom(SALT_SIZE)
                key = derive(password, salt)
                    f = Fernet(key)
                        enc = f.encrypt(json.dumps(data).encode())
                            return {"salt": base64.b64encode(salt).decode(), "data": base64.b64encode(enc).decode()}

                            def decrypt_vault(blob, password):
                                salt = base64.b64decode(blob["salt"])
                                    enc = base64.b64decode(blob["data"])
                                        key = derive(password, salt)
                                            f = Fernet(key)
                                                raw = f.decrypt(enc)
                                                    return json.loads(raw.decode())

                                                    def load(password):
                                                        if not os.path.exists(VAULT_FILE):
                                                                return {}
                                                                    try:
                                                                            with open(VAULT_FILE) as f:
                                                                                        blob = json.load(f)
                                                                                                return decrypt_vault(blob, password)
                                                                                                    except:
                                                                                                            raise InvalidToken

                                                                                                            def save(data, password):
                                                                                                                blob = encrypt_vault(data, password)
                                                                                                                    tmp = VAULT_FILE + ".tmp"
                                                                                                                        with open(tmp, "w") as f:
                                                                                                                                json.dump(blob, f)
                                                                                                                                    os.replace(tmp, VAULT_FILE)

                                                                                                                                    def make_password(n=16):
                                                                                                                                        chars = string.ascii_letters + string.digits + string.punctuation
                                                                                                                                            return "".join(random.choice(chars) for _ in range(n))

                                                                                                                                            def main():
                                                                                                                                                print("==== Simple Password Manager ====")
                                                                                                                                                    pw = input("Master password: ")

                                                                                                                                                        try:
                                                                                                                                                                vault = load(pw)
                                                                                                                                                                    except InvalidToken:
                                                                                                                                                                            print("Bad master password or broken vault.")
                                                                                                                                                                                    return

                                                                                                                                                                                        while True:
                                                                                                                                                                                                print("\n1) Add password")
                                                                                                                                                                                                        print("2) View one")
                                                                                                                                                                                                                print("3) View ALL passwords")
                                                                                                                                                                                                                        print("4) List services only")
                                                                                                                                                                                                                                print("5) Delete")
                                                                                                                                                                                                                                        print("6) Generate password")
                                                                                                                                                                                                                                                print("7) Exit")

                                                                                                                                                                                                                                                        ch = input("Choose: ").strip()

                                                                                                                                                                                                                                                                if ch == "1":
                                                                                                                                                                                                                                                                            name = input("Service: ").strip().lower()
                                                                                                                                                                                                                                                                                        if not name: 
                                                                                                                                                                                                                                                                                                        print("Bad name."); continue
                                                                                                                                                                                                                                                                                                                    u = input("Username: ").strip()
                                                                                                                                                                                                                                                                                                                                p = input("Password (visible): ").strip()
                                                                                                                                                                                                                                                                                                                                            vault[name] = {"username": u, "password": p}
                                                                                                                                                                                                                                                                                                                                                        save(vault, pw)
                                                                                                                                                                                                                                                                                                                                                                    print("Saved.")

                                                                                                                                                                                                                                                                                                                                                                            elif ch == "2":
                                                                                                                                                                                                                                                                                                                                                                                        name = input("Service: ").strip().lower()
                                                                                                                                                                                                                                                                                                                                                                                                    if name not in vault:
                                                                                                                                                                                                                                                                                                                                                                                                                    print("Not found.")
                                                                                                                                                                                                                                                                                                                                                                                                                                    continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                entry = vault[name]
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\nService:", name)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Username:", entry["username"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Password:", entry["password"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif ch == "3":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not vault:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Vault empty.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n=== All Accounts ===")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for s, v in vault.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"\nService: {s}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("  Username:", v["username"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("  Password:", v["password"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif ch == "4":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not vault:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Nothing saved.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\nServices:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for s in sorted(vault.keys()):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("-", s)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif ch == "5":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name = input("Delete which service: ").strip().lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if name in vault:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    del vault[name]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    save(vault, pw)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Deleted.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Not found.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif ch == "6":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raw = input("Length (default 16): ").strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                n = int(raw) if raw.isdigit() else 16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pwd = make_password(n)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\nGenerated:", pwd)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif ch == "7":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Bye.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Invalid option.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()